### ISSUE TITLE
Memory footprint grows indefinitely

### ISSUE THREAD

**Issue by StephenThomson** [oasis-open/cti-stix-elevator#63]
If left running the memory footprint will grow indefinitely. I investigated the issue with heapy.

The type taking most of the space is dictionaries:
```
	 Partition of a set of 513745 objects. Total size = 130115120 bytes.                                                   
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)                                             
     0  41241   8 63649752  49  63649752  49 dict (no owner)                                                          
     1 153068  30 12261576   9  75911328  58 str           
     2  88333  17  7873408   6  83784736  64 tuple         
     3  14425   3  6690568   5  90475304  70 list          
     4  24848   5  3180544   2  93655848  72 types.CodeType                                                           
     5   2422   0  3025168   2  96681016  74 dict of type  
     6  24896   5  2987520   2  99668536  77 function      
     7   9417   2  2636760   2 102305296  79 dict of 0x23d2080                                                        
     8   2423   0  2186576   2 104491872  80 type          
     9    774   0  2088336   2 106580208  82 dict of module
```
Investigation the dictionaries show that most were cybox objects:
```
>>> h[0].byrcs                                             
Partition of a set of 41241 objects. Total size = 63649752 bytes.                                                     
 Index  Count   %     Size   % Cumulative  % Referrers by Kind (class / dict of class)                                
     0      1   0 25166104  40  25166104  40 dict of cybox.utils.caches.DictCache                                     
     1   2350   6  7877200  12  33043304  52 dict of cybox.objects.file_object.File                                   
     2   5140  12  5386720   8  38430024  60 dict of cybox.core.observable.Observable                                 
     3   4397  11  4608056   7  43038080  68 dict of cybox.common.properties.HexBinary                                
     4   4397  11  4608056   7  47646136  75 dict of cybox.common.vocabs.HashName                                     
     5   3695   9  3872360   6  51518496  81 dict of cybox.common.properties.String                                   
     6   2047   5  2145256   3  53663752  84 dict of cybox.common.properties.UnsignedLong                             
     7    318   1  1969488   3  55633240  87 dict of module                                                           
     8   4397  11  1231160   2  56864400  89 dict of cybox.common.hashes.Hash                                         
     9   1124   3  1177952   2  58042352  91 dict of cybox.common.properties.AnyURI 
```

**Comment by rpiazza** [comment]
The elevator was written as an experimental tool for users to become familiar with STIX 2.0, assuming they had some familiarity with STIX 1.x.  That being said, we do plan to improve performance in the next major version - so we will definitely look into memory issues.

**Comment by StephenThomson** [comment]
@rpiazza Thanks for getting back to me. Great news that you will be looking in to it. I do understand that this isn't a production ready product. I wasn't expecting a fix, I just thought it was worth raising an issue.

**Comment by gtback** [comment]
Based on the data above, I'm going to guess it's related to CybOXProject/python-cybox#290. There's a workaround in that issue discussion (un-setting a post-set hook), and will hopefully be fixed by default in the next python-cybox.

@StephenThomson, can you try that workaround?

**Comment by StephenThomson** [comment]
Thanks very much for your help.

I'm running that now, I'll update with results.

**Comment by StephenThomson** [comment]
Unfortunately it didn't seem to help. A quick look through the code suggests there a few dictionaries lying around that get added to but seem to never be managed e.g. OBSERVABLE_MAPPING in convert_stix.py

**Comment by gtback** [comment]
Hmmm, yes, it looks like those could grow indefinitely. You could probably write some code to throw away that "context" whenever you're done with it (probably on a per-document basis), but this is something we should make it easier to do.

**Comment by rpiazza** [comment]
Thanks - this is an actual bug - see elevate_file where we clear the mappings - guess we missed one.  All of these global maps should go away in the performance release.

**Comment by gtback** [comment]
Thanks, @rpiazza, I knew I had seen code to do that somewhere, but I didn't find it in a brief search this morning.

**Comment by rpiazza** [comment]
I fixed the issue with OBSERVABLE_MAPPING in https://github.com/oasis-open/cti-stix-elevator/commit/b2cb9f22f867c9b0232943d67f36acae24448aea.
Please inform us if you encounter any other memory leaks.

**Comment by StephenThomson** [comment]
Hi,

Thanks for the fix, I've tested it and the memory performance is much better now.

However I think there is still a problem. I wrote a quick test script to highlight it:

```
from cybox.core import Object
from stix2elevator import elevate_string,options
import time
import thread
from guppy import hpy

heapy = hpy()
heap = heapy.heap()
Object.id_.postset_hook = None

def run():
    xml_input_file = open('1.xml', 'r')
    xml_string = xml_input_file.read()
    options.initialize_options()
    for xml_idx in range(1,50000):
        elevate_string(xml_string)

thread.start_new_thread(run,())

while 1:
    try:
        output = open("output", "a")
        output.write(str(heap))
        output.close()
        time.sleep(300)
    except KeyboardInterrupt:
        output.close()
        break
```

The output was:
```
Partition of a set of 301744 objects. Total size = 39487624 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 109823  36  9007296  23   9007296  23 str
     1  81677  27  7291096  18  16298392  41 tuple
     2  23223   8  2972544   8  19270936  49 types.CodeType
     3   2200   1  2847040   7  22117976  56 dict of type
     4  23113   8  2773560   7  24891536  63 function
     5   2138   1  2607344   7  27498880  70 dict (no owner)
     6   2200   1  1985080   5  29483960  75 type
     7    695   0  1852712   5  31336672  79 dict of module
     8   1072   0  1123456   3  32460128  82 dict of mixbox.fields.TypedField
     9   4158   1   588912   1  33049040  84 list
<494 more rows. Type e.g. '_.more' to view.>Partition of a set of 301744 objects. Total size = 39676720 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 109823  36  9007296  23   9007296  23 str
     1  81677  27  7291096  18  16298392  41 tuple
     2  23223   8  2972544   7  19270936  49 types.CodeType
     3   2200   1  2848576   7  22119512  56 dict of type
     4  23113   8  2773560   7  24893072  63 function
     5   2297   1  2674904   7  27567976  69 dict (no owner)
     6   2200   1  1985080   5  29553056  74 type
     7    695   0  1855016   5  31408072  79 dict of module
     8   1072   0  1123456   3  32531528  82 dict of mixbox.fields.TypedField
     9   4158   1   753776   2  33285304  84 list
<494 more rows. Type e.g. '_.more' to view.>Partition of a set of 301744 objects. Total size = 39840560 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 109823  36  9007296  23   9007296  23 str
     1  81677  27  7291096  18  16298392  41 tuple
     2  23223   8  2972544   7  19270936  48 types.CodeType
     3   2200   1  2848576   7  22119512  56 dict of type
     4  23113   8  2773560   7  24893072  62 function
     5   2297   1  2674904   7  27567976  69 dict (no owner)
     6   2200   1  1985080   5  29553056  74 type
     7    695   0  1855016   5  31408072  79 dict of module
     8   1072   0  1123456   3  32531528  82 dict of mixbox.fields.TypedField
     9   4158   1   917616   2  33449144  84 list
<494 more rows. Type e.g. '_.more' to view.>Partition of a set of 301744 objects. Total size = 39938864 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 109823  36  9007296  23   9007296  23 str
     1  81677  27  7291096  18  16298392  41 tuple
     2  23223   8  2972544   7  19270936  48 types.CodeType
     3   2200   1  2848576   7  22119512  55 dict of type
     4  23113   8  2773560   7  24893072  62 function
     5   2297   1  2674904   7  27567976  69 dict (no owner)
     6   2200   1  1985080   5  29553056  74 type
     7    695   0  1855016   5  31408072  79 dict of module
     8   1072   0  1123456   3  32531528  81 dict of mixbox.fields.TypedField
     9   4158   1  1015920   3  33547448  84 list
<494 more rows. Type e.g. '_.more' to view.>
```

You can see that there is a problem with list objects growing. I will continue to investigate and hopefully come back with some better information soon.

Thanks,

ST

**Comment by gtback** [comment]
Thanks, I'll re-open this until we/you can track it down.

**Comment by gtback** [comment]
This might have been fixed by #90, but I'd like to confirm before closing.
